version: '3.9'

services:
  geolocationapi:
    container_name: geolocationapi
    image: geolocationapi
    build: .
    volumes:
      - .:/code
    ports:
      - '8080:8080'
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - API_KEY=API_KEY
    depends_on:
      - db
    command: flask run --host=0.0.0.0 --port=8080

  db:
    container_name: db
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
