version: '3.9'

services:
  geolocationapi:
    container_name: geolocationapi
    restart: always
    image: geolocationapi
    build: .
    volumes:
      - .:/code
    ports:
      - '8080:8080'
    env_file:
      - ./.env
    environment:
      - FLASK_ENV=docker
    depends_on:
      - postgres
    command: >
      sh -c "python -m unittest discover &&
             flask run --host=0.0.0.0 --port=8080"

  postgres:
    container_name: postgres
    restart: always
    image: postgres:14.1
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - geolocationapi-db:/var/lib/postgresql/data
volumes:
  geolocationapi-db:
    name: geolocationapi-db
