version: '3.9'

services:
  geolocationapi:
    container_name: geolocationapi
    image: geolocationapi
    build: .
    ports:
      - '80:80'
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - API_KEY=AIzaSyCKtYFCg2G6csgW8xetgUGQSvgCVqUTlRM
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
